version: '2'
services:
    report-app:
        image: report
        external_links:
            - report-mongodb:mongodb
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=report
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    report-mongodb:
        extends:
            file: mongodb.yml
            service: report-mongodb
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
